#serving size and nutritional facts grabbed from https://www.nutritionix.com/

dataset = {
    "Apple": {"serving size": '1 medium (182g)'
              , "calories": '95kcal', "total fat": '0.3g', "protein": '0.5g', "carbs": '25g'},
    "Banana": {"serving size": '1 medium (118g)', 
               "calories": '105kcal', "total fat": '0.3g', "protein": '1.3g', "carbs": '27g'},
    "Apricot": {"serving size": '4 apricots (100g)',
                "calories": '48kcal', "total fat": '0.1g', "protein": '1.4g', "carbs": '12g'},
    "Avocado": {"serving size": '1 medium (150g)', 
                "calories": '240kcal', "total fat": '22g', "protein": '3g', "carbs": '12g'},
    "Beetroot": {"serving size": '1 medium (100g)', 
                 "calories": '43kcal', "total fat": '0.2g', "protein": '1.6g', "carbs": '10g'},
    "Blueberry": {"serving size": '1 cup (148g)', 
                  "calories": '85kcal', "total fat": '0.5g', "protein": '1.1g', "carbs": '21g'},
    "Cabbage": {"serving size": '1 cup shredded (70g)', 
                "calories": '17kcal', "total fat": '0.1g', "protein": '1g', "carbs": '4g'},
    "Cactus": {"serving size": '1 cup (100g)', 
               "calories": '16kcal', "total fat": '0.2g', "protein": '0.7g', "carbs": '3.7g'},
    "Cantaloupe": {"serving size": '1 cup (100g)', 
                   "calories": '34kcal', "total fat": '0.2g', "protein": '0.8g', "carbs": '8g'},
    "Carambula": {"serving size": '1 medium (100g)', 
                  "calories": '31kcal', "total fat": '0.4g', "protein": '0.9g', "carbs": '7g'},
    "Carrot": {"serving size": '1 medium (61g)', "calories": '25kcal', "total fat": '0.1g', "protein": '0.6g', "carbs": '6g'},
    "Cauliflower": {"serving size": '1 cup (100g)', 
                    "calories": '25kcal', "total fat": '0.3g', "protein": '1.9g', "carbs": '5g'},
    "Cherry": {"serving size": '1 cup (154g)', 
               "calories": '77kcal', "total fat": '0.2g', "protein": '1.6g', "carbs": '20g'},
    "Chestnut": {"serving size": '1 cup (100g)', 
                 "calories": '213kcal', "total fat": '2.2g', "protein": '2.4g', "carbs": '45g'},
    "Clementine": {"serving size": '1 medium (74g)', 
                   "calories": '35kcal', "total fat": '0.2g', "protein": '0.6g', "carbs": '9g'},
    "Coconut": {"serving size": '1/2 medium (80g)', 
                "calories": '354kcal', "total fat": '33g', "protein": '3g', "carbs": '15g'},
    "Corn": {"serving size": '1 medium ear (100g)', 
             "calories": '96kcal', "total fat": '1.5g', "protein": '3.4g', "carbs": '21g'},
    "Cucumber": {"serving size": '1 medium (100g)', 
                 "calories": '16kcal', "total fat": '0.1g', "protein": '0.7g', "carbs": '3.6g'},
    "Dates": {"serving size": '1 date (24g)',
              "calories": '23kcal', "total fat": '0.1g', "protein": '0.2g', "carbs": '6g'},
    "Eggplant": {"serving size": '1 medium (100g)', 
                 "calories": '25kcal', "total fat": '0.2g', "protein": '1g', "carbs": '6g'},
    "Fig": {"serving size": '2 figs (100g)', 
            "calories": '74kcal', "total fat": '0.3g', "protein": '0.8g', "carbs": '19g'},
    "Ginger": {"serving size": '1 oz (28g)', 
               "calories": '22kcal', "total fat": '0.2g', "protein": '0.5g', "carbs": '5g'},
    "Granadilla": {"serving size": '1 fruit (100g)', 
                   "calories": '97kcal', "total fat": '0.4g', "protein": '2g', "carbs": '23g'},
    "Grape": {"serving size": '1 cup (151g)', 
              "calories": '104kcal', "total fat": '0.2g', "protein": '1.1g', "carbs": '27g'},
    "Grapefruit": {"serving size": '1/2 medium (123g)', 
                   "calories": '42kcal', "total fat": '0.1g', "protein": '0.8g', "carbs": '11g'},
    "Guava": {"serving size": '1 medium (250g)', 
              "calories": '68kcal', "total fat": '0.6g', "protein": '2.6g', "carbs": '14g'},
    "Hazelnut": {"serving size": '1 oz (28g)', 
                 "calories": '178kcal', "total fat": '17g', "protein": '4g', "carbs": '5g'},
    "Huckleberry": {"serving size": '1 cup (148g)', 
                    "calories": '70kcal', "total fat": '0.3g', "protein": '1g', "carbs": '17g'},
    "Kaki": {"serving size": '1 medium (100g)', 
             "calories": '81kcal', "total fat": '0.3g', "protein": '0.6g', "carbs": '22g'},
    "Kiwi": {"serving size": '1 medium (76g)', 
             "calories": '42kcal', "total fat": '0.4g', "protein": '0.8g', "carbs": '10g'},
    "Kohlrabi": {"serving size": '1 medium (100g)', 
                 "calories": '27kcal', "total fat": '0.1g', "protein": '2g', "carbs": '6g'},
    "Kumquat": {"serving size": '5 fruits (100g)', 
                "calories": '71kcal', "total fat": '0.5g', "protein": '0.8g', "carbs": '16g'},
    "Lemon": {"serving size": '1 medium (100g)', 
              "calories": '29kcal', "total fat": '0.3g', "protein": '1.1g', "carbs": '9g'},
    "Lime": {"serving size": '1 medium (100g)', 
             "calories": '30kcal', "total fat": '0.2g', "protein": '0.99g', "carbs": '7g'},
    "Lychee": {"serving size": '1 cup (190g)', 
               "calories": '66kcal', "total fat": '0.4g', "protein": '0.8g', "carbs": '16g'},
    "Mandarine": {"serving size": '1 medium (88g)', 
                  "calories": '38kcal', "total fat": '0.2g', "protein": '0.6g', "carbs": '9g'},
    "Mango": {"serving size": '1 medium (200g)', 
              "calories": '150kcal', "total fat": '0.6g', "protein": '1.6g', "carbs": '39g'},
    "Maracuja": {"serving size": '1 fruit (100g)', 
                 "calories": '97kcal', "total fat": '0.4g', "protein": '2.2g', "carbs": '24g'},
    "Melon Piel De Sapo": {"serving size": '1 cup (100g)', "calories": '34kcal', "total fat": '0.2g', "protein": '0.5g', "carbs": '8g'},
    "Mulberry": {"serving size": '1 cup (100g)',
                 "calories": '43kcal', "total fat": '0.4g', "protein": '2.1g', "carbs": '9.8g'},
    "Nectarine": {"serving size": '1 medium (150g)', 
                  "calories": '44kcal', "total fat": '0.3g', "protein": '0.9g', "carbs": '10g'},
    "Brazil Nut": {"serving size": '1 oz (28g)', 
                   "calories": '187kcal', "total fat": '19g', "protein": '4g', "carbs": '3.5g'},
    "Pecan Nut": {"serving size": '1 oz (28g)', 
                  "calories": '196kcal', "total fat": '20g', "protein": '3g', "carbs": '4g'},
    "Papaya": {"serving size": '1 medium (148g)', 
               "calories": '59kcal', "total fat": '0.4g', "protein": '0.5g', "carbs": '15g'},
    "Onion": {"serving size": '1 medium (110g)', 
              "calories": '44kcal', "total fat": '0.1g', "protein": '1.2g', "carbs": '10g'},
    "Orange": {"serving size": '1 medium (131g)', 
               "calories": '62kcal', "total fat": '0.2g', "protein": '1.2g', "carbs": '15g'},
    "Passion Fruit": {"serving size": '1 medium (100g)', 
                      "calories": '97kcal', "total fat": '0.4g', "protein": '2.2g', "carbs": '24g'},
    "Peach": {"serving size": '1 medium (150g)', 
              "calories": '58kcal', "total fat": '0.4g', "protein": '1.4g', "carbs": '14g'},
    "Pear": {"serving size": '1 medium (178g)', 
             "calories": '102kcal', "total fat": '0.2g', "protein": '0.6g', "carbs": '28g'},
    "Pepino": {"serving size": '1 medium (100g)', 
               "calories": '50kcal', "total fat": '0.2g', "protein": '1g', "carbs": '12g'},
    "Pepper": {"serving size": '1 medium (150g)', 
               "calories": '31kcal', "total fat": '0.3g', "protein": '1g', "carbs": '6g'},
    "Physalis": {"serving size": '1 cup (100g)', 
                 "calories": '81kcal', "total fat": '0.5g', "protein": '2.1g', "carbs": '18g'},
    "Pineapple": {"serving size": '1 cup (100g)', 
                  "calories": '50kcal', "total fat": '0.1g', "protein": '0.5g', "carbs": '13g'},
    "Pithaya": {"serving size": '1 medium (100g)', 
                "calories": '60kcal', "total fat": '0.1g', "protein": '1.2g', "carbs": '13g'},
    "Plum": {"serving size": '1 medium (66g)', 
             "calories": '46kcal', "total fat": '0.3g', "protein": '0.7g', "carbs": '11g'},
    "Pomegranate": {"serving size": '1 medium (282g)', 
                    "calories": '83kcal', "total fat": '1.2g', "protein": '1.7g', "carbs": '19g'},
    "Oroblanco": {"serving size": '1 medium (100g)', 
                  "calories": '80kcal', "total fat": '0.1g', "protein": '1g', "carbs": '20g'},
    "Red Potato": {"serving size": '1 medium (150g)', 
                   "calories": '77kcal', "total fat": '0.1g', "protein": '2g', "carbs": '17g'},
    "White Potato": {"serving size": '1 medium (150g)', 
                     "calories": '77kcal', "total fat": '0.1g', "protein": '2g', "carbs": '17g'},
    "Sweet Potato": {"serving size": '1 medium (130g)', 
                     "calories": '86kcal', "total fat": '0.1g', "protein": '1.6g', "carbs": '20g'},
    "Quince": {"serving size": '1 medium (100g)', 
               "calories": '57kcal', "total fat": '0.1g', "protein": '0.4g', "carbs": '15g'},
    "Rambutan": {"serving size": '1 medium (100g)', 
                 "calories": '68kcal', "total fat": '0.2g', "protein": '0.9g', "carbs": '16g'},
    "Raspberry": {"serving size": '1 cup (123g)', 
                  "calories": '52kcal', "total fat": '0.7g', "protein": '1.2g', "carbs": '12g'},
    "Redcurrant": {"serving size": '1 cup (100g)', 
                   "calories": '56kcal', "total fat": '0.3g', "protein": '1g', "carbs": '13g'},
    "Salak": {"serving size": '1 fruit (100g)', 
              "calories": '82kcal', "total fat": '0.2g', "protein": '0.5g', "carbs": '23g'},
    "Strawberry": {"serving size": '1 cup (152g)', 
                   "calories": '49kcal', "total fat": '0.5g', "protein": '1g', "carbs": '11g'},
    "Tamarillo": {"serving size": '1 medium (100g)', 
                  "calories": '50kcal', "total fat": '0.2g', "protein": '1.6g', "carbs": '12g'},
    "Tangelo": {"serving size": '1 medium (100g)', 
                "calories": '40kcal', "total fat": '0.1g', "protein": '0.6g', "carbs": '10g'},
    "Tomato": {"serving size": '1 medium (123g)', 
               "calories": '22kcal', "total fat": '0.2g', "protein": '1g', "carbs": '5g'},
    "Cherry Tomato": {"serving size": '1 cup (149g)', 
                      "calories": '27kcal', "total fat": '0.3g', "protein": '1.3g', "carbs": '6g'},
    "Walnut": {"serving size": '1 oz (28g)', 
               "calories": '654kcal', "total fat": '65g', "protein": '15g', "carbs": '14g'},
    "Watermelon": {"serving size": '1 wedge (286g)', 
                   "calories": '86kcal', "total fat": '0.2g', "protein": '1.7g', "carbs": '22g'},
    "Zucchini": {"serving size": '1 medium (196g)', 
                 "calories": '33kcal', "total fat": '0.4g', "protein": '2.4g', "carbs": '6g'},
}